name: Push File

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes _book folder
      uses: datalbry/copy_folder_to_another_repo_action@1.0.0
      env:
        API_TOKEN_GITHUB: ${{ secrets.PUSH_TOKEN }}
      with:
        source_folder: '_book'
        destination_repo: 'haideraliakmal/phd-thesis-source'
        destination_folder: './'
        user_email: 'haider.ali.akmal@gmail.com'
        user_name: 'haideraliakmal'
        commit_msg: 'Copied files over from source'
